-- Q1:
CREATE TABLE DEPARTAMENTS
         (	NUM_DPT INTEGER,
	NOM_DPT CHAR(20),
	PLANTA INTEGER,
	EDIFICI CHAR(30),
	CIUTAT_DPT CHAR(20),
	PRIMARY KEY (NUM_DPT));

CREATE TABLE PROJECTES
         (	NUM_PROJ INTEGER,
	NOM_PROJ CHAR(10),
	PRODUCTE CHAR(20),
	PRESSUPOST INTEGER,
	PRIMARY KEY (NUM_PROJ));

CREATE TABLE EMPLEATS
         (	NUM_EMPL INTEGER,
	NOM_EMPL CHAR(30),
	SOU INTEGER,
	CIUTAT_EMPL CHAR(20),
	NUM_DPT INTEGER,
	NUM_PROJ INTEGER,
	PRIMARY KEY (NUM_EMPL),
	FOREIGN KEY (NUM_DPT) REFERENCES DEPARTAMENTS (NUM_DPT),
	FOREIGN KEY (NUM_PROJ) REFERENCES PROJECTES (NUM_PROJ));

INSERT INTO  DEPARTAMENTS VALUES (5,'VENDES',3,'MUNTANER','MADRID');

INSERT INTO  EMPLEATS VALUES (3,'MANEL',250000,'MADRID',5,null);

/*
Doneu una seqüència d'operacions d'algebra relacional per obtenir els números i els noms dels departament situats a MADRID, 
que tenen algun empleat que guanya més de 200000. 

Pel joc de proves que trobareu al fitxer adjunt, la sortida ha de ser:

Num_dpt		Nom_dpt
5		VENDES
*/

-- Solución:
A=EMPLEATS(SOU>200000)
B=DEPARTAMENTS(CIUTAT_DPT='MADRID')
C=A*B
R=C[NUM_DPT,NOM_DPT]



-- Q2:
CREATE TABLE DEPARTAMENTS
         (	NUM_DPT INTEGER,
	NOM_DPT CHAR(20),
	PLANTA INTEGER,
	EDIFICI CHAR(30),
	CIUTAT_DPT CHAR(20),
	PRIMARY KEY (NUM_DPT));

CREATE TABLE PROJECTES
         (	NUM_PROJ INTEGER,
	NOM_PROJ CHAR(10),
	PRODUCTE CHAR(20),
	PRESSUPOST INTEGER,
	PRIMARY KEY (NUM_PROJ));

CREATE TABLE EMPLEATS
         (	NUM_EMPL INTEGER,
	NOM_EMPL CHAR(30),
	SOU INTEGER,
	CIUTAT_EMPL CHAR(20),
	NUM_DPT INTEGER,
	NUM_PROJ INTEGER,
	PRIMARY KEY (NUM_EMPL),
	FOREIGN KEY (NUM_DPT) REFERENCES DEPARTAMENTS (NUM_DPT),
	FOREIGN KEY (NUM_PROJ) REFERENCES PROJECTES (NUM_PROJ));

INSERT INTO PROJECTES VALUEs (
1,'IBDTEL','TELEVISIO',1000000);

/*
Doneu una seqüència d'operacions d'àlgebra relacional per obtenir els noms i números dels projectes que no tenen cap empleat assignat. 

Pel joc de proves que trobareu al fitxer adjunt, la sortida seria:

Nom_proj		Num_proj
IBDTEL		1
*/

-- Solución:
A=PROJECTES*EMPLEATS
B=A[NUM_PROJ,NOM_PROJ,PRODUCTE,PRESSUPOST]
C=PROJECTES-B
R=C[NOM_PROJ,NUM_PROJ]



-- Q3:
CREATE TABLE DEPARTAMENTS
         (	NUM_DPT INTEGER,
	NOM_DPT CHAR(20),
	PLANTA INTEGER,
	EDIFICI CHAR(30),
	CIUTAT_DPT CHAR(20),
	PRIMARY KEY (NUM_DPT));

CREATE TABLE PROJECTES
         (	NUM_PROJ INTEGER,
	NOM_PROJ CHAR(10),
	PRODUCTE CHAR(20),
	PRESSUPOST INTEGER,
	PRIMARY KEY (NUM_PROJ));

CREATE TABLE EMPLEATS
         (	NUM_EMPL INTEGER,
	NOM_EMPL CHAR(30),
	SOU INTEGER,
	CIUTAT_EMPL CHAR(20),
	NUM_DPT INTEGER,
	NUM_PROJ INTEGER,
	PRIMARY KEY (NUM_EMPL),
	FOREIGN KEY (NUM_DPT) REFERENCES DEPARTAMENTS (NUM_DPT),
	FOREIGN KEY (NUM_PROJ) REFERENCES PROJECTES (NUM_PROJ));
	
	
INSERT INTO  DEPARTAMENTS VALUES (3,'MARKETING',3,'RIOS ROSAS','BARCELONA');

INSERT INTO  EMPLEATS VALUES (3,'ROBERTO',25000,'BARCELONA',3,null);

/*
Doneu una seqüència d'operacions d'algebra relacional per obtenir el número i el nom dels empleats que viuen a la mateixa 
ciutat on està situat el departament on treballen.

Pel joc de proves que trobareu al fitxer adjunt, la sortida seria:

NOM_empl        NUM_empl
ROBERTO         3
*/

-- Solución:
A=EMPLEATS{NUM_DPT->NUM_DPT_EMPL}
B=A[NUM_DPT_EMPL=NUM_DPT, CIUTAT_EMPL=CIUTAT_DPT]DEPARTAMENTS
R=B[NOM_EMPL,NUM_EMPL]
